version: "3"

networks:
  app-tier:
    driver: bridge

services:
  server:
    build:
      context: .
      dockerfile: server.Dockerfile
      container_name: chat_server
      ports:
        - 
      volumes:
        # - ./ 
      environment:
        # - ={}
      networks:
      - app-tier

  storage:
    build:
      image: 'bitnami/etcd:latest'
      container_name: chat_storage
      ports:
        - 2379:2379
        - 2380:2380
      volumes:
        - ./storage:/opt/bitnami/etcd/conf/etcd.conf.yml
      environment:
        - ALLOW_NONE_AUTHENTICATION=yes
        - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
      