version: "3"

networks:
  app-tier:
    driver: bridge

services:
  storage:
    image: 'bitnami/etcd:latest'
    container_name: chat_storage
    ports:
      - 2379:2379
      - 2380:2380
    env_file:
      - ./etc/.env
    networks:
      - app-tier

  server:
    build:
      context: .
      dockerfile: ./chat_docker/server/Dockerfile
    container_name: chat_server
    ports:
      - 50051:50051
    env_file:
      - ./etc/.env
    networks:
      - app-tier
    restart: on-failure
    depends_on:
      - storage
