# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chat.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='chat.proto',
  package='chat',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\nchat.proto\x12\x04\x63hat\"-\n\tUsersList\x12\r\n\x05login\x18\x01 \x01(\t\x12\x11\n\tfull_name\x18\x02 \x01(\t\"\'\n\rReceiptStatus\x12\x16\n\x0ereceipt_status\x18\x01 \x01(\t\"\x15\n\x04User\x12\r\n\x05login\x18\x01 \x01(\t\"P\n\x0b\x43hatMessage\x12\x11\n\tuser_from\x18\x01 \x01(\t\x12\x0f\n\x07user_to\x18\x02 \x01(\t\x12\x0f\n\x07time_on\x18\x03 \x01(\x05\x12\x0c\n\x04\x62ody\x18\x04 \x01(\t2\xa9\x01\n\x07Greeter\x12\x32\n\x08GetUsers\x12\x0f.chat.UsersList\x1a\x13.chat.ReceiptStatus\"\x00\x12.\n\x0bSendMessage\x12\n.chat.User\x1a\x11.chat.ChatMessage\"\x00\x12:\n\x0cListMessages\x12\x11.chat.ChatMessage\x1a\x13.chat.ReceiptStatus\"\x00(\x01\x62\x06proto3'
)




_USERSLIST = _descriptor.Descriptor(
  name='UsersList',
  full_name='chat.UsersList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='login', full_name='chat.UsersList.login', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='full_name', full_name='chat.UsersList.full_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=65,
)


_RECEIPTSTATUS = _descriptor.Descriptor(
  name='ReceiptStatus',
  full_name='chat.ReceiptStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='receipt_status', full_name='chat.ReceiptStatus.receipt_status', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=106,
)


_USER = _descriptor.Descriptor(
  name='User',
  full_name='chat.User',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='login', full_name='chat.User.login', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=108,
  serialized_end=129,
)


_CHATMESSAGE = _descriptor.Descriptor(
  name='ChatMessage',
  full_name='chat.ChatMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_from', full_name='chat.ChatMessage.user_from', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='user_to', full_name='chat.ChatMessage.user_to', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='time_on', full_name='chat.ChatMessage.time_on', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='body', full_name='chat.ChatMessage.body', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=131,
  serialized_end=211,
)

DESCRIPTOR.message_types_by_name['UsersList'] = _USERSLIST
DESCRIPTOR.message_types_by_name['ReceiptStatus'] = _RECEIPTSTATUS
DESCRIPTOR.message_types_by_name['User'] = _USER
DESCRIPTOR.message_types_by_name['ChatMessage'] = _CHATMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UsersList = _reflection.GeneratedProtocolMessageType('UsersList', (_message.Message,), {
  'DESCRIPTOR' : _USERSLIST,
  '__module__' : 'chat_pb2'
  # @@protoc_insertion_point(class_scope:chat.UsersList)
  })
_sym_db.RegisterMessage(UsersList)

ReceiptStatus = _reflection.GeneratedProtocolMessageType('ReceiptStatus', (_message.Message,), {
  'DESCRIPTOR' : _RECEIPTSTATUS,
  '__module__' : 'chat_pb2'
  # @@protoc_insertion_point(class_scope:chat.ReceiptStatus)
  })
_sym_db.RegisterMessage(ReceiptStatus)

User = _reflection.GeneratedProtocolMessageType('User', (_message.Message,), {
  'DESCRIPTOR' : _USER,
  '__module__' : 'chat_pb2'
  # @@protoc_insertion_point(class_scope:chat.User)
  })
_sym_db.RegisterMessage(User)

ChatMessage = _reflection.GeneratedProtocolMessageType('ChatMessage', (_message.Message,), {
  'DESCRIPTOR' : _CHATMESSAGE,
  '__module__' : 'chat_pb2'
  # @@protoc_insertion_point(class_scope:chat.ChatMessage)
  })
_sym_db.RegisterMessage(ChatMessage)



_GREETER = _descriptor.ServiceDescriptor(
  name='Greeter',
  full_name='chat.Greeter',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=214,
  serialized_end=383,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetUsers',
    full_name='chat.Greeter.GetUsers',
    index=0,
    containing_service=None,
    input_type=_USERSLIST,
    output_type=_RECEIPTSTATUS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SendMessage',
    full_name='chat.Greeter.SendMessage',
    index=1,
    containing_service=None,
    input_type=_USER,
    output_type=_CHATMESSAGE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ListMessages',
    full_name='chat.Greeter.ListMessages',
    index=2,
    containing_service=None,
    input_type=_CHATMESSAGE,
    output_type=_RECEIPTSTATUS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_GREETER)

DESCRIPTOR.services_by_name['Greeter'] = _GREETER

# @@protoc_insertion_point(module_scope)
